openapi: "3.0.0"
info:
  title: Super Deals
  version: "1.0"
tags:
  - name: deals
    description: Deals service
components:
  schemas:
    Deal:
      type: object
      description: A deal added by a merchant
      required:
        - merchantId
        - title
        - originalPrice
        - discount
        - logo
        - category
        - expiration
      properties:
        merchantId:
          type: string
          description: ID of merchant who created the deal
        title:
          type: string
          description: Title of the deal
        originalPrice:
          type: number
          description: Original price of the deal
        discount:
          type: number
          description: Deal discount
        logo:
          type: object
          description: Logo image of the deal
        category:
          type: string
          description: The category this deal falls under
        expiration:
          type: number
          description: The expiration date of the deal
    merchant:
      type: object
      description: Data about merchant
servers:
  - url: https://mms6a4j564.execute-api.us-east-1.amazonaws.com/prod/
    description: Basepath
paths:
  /account/sign-up:
    description: Consumers can sign up for an account
    post:
      tags:
        - account
      description: Submit sign up form
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/account"
      responses:
        "200":
          description: Successfully signed up user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/account"
